mysite/myapp/urls.py
from django.urls import path
from myapp.views import (
    TechHome,
    TechCategory,
    ShowProduct,
    addProduct,
    UpdateProduct,
    DeleteProduct,
)

app_name = "myapp"

urlpatterns = [
    path("", TechHome.as_view(), name="home"),
    path("search/", TechCategory.as_view(), name="search"),
    path("<slug:category_slug>/", TechCategory.as_view(), name="category"),
    path("product/add_product/", addProduct.as_view(), name="addPage"),
    path("product/<slug:product_slug>/", ShowProduct.as_view(), name="product"),
    path("product/<slug:slug>/update/", UpdateProduct.as_view(), name="updatePage"),
    path("product/<slug:slug>/delete/", DeleteProduct.as_view(), name="deletePage"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("myapp.urls", namespace="myapp")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Добро пожаловать в панель администрирования сайта"

mysite/users/urls.py
from django.urls import path
from .views import LoginUser
from django.contrib.auth.views import LogoutView

app_name = "users"

urlpatterns = [
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

mysite/myapp/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(max_length=1000, verbose_name="Описание")
    price = models.IntegerField(verbose_name="Цена")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    is_published = models.BooleanField(default=True, verbose_name="Опубликованно")
    image = models.ImageField(
        upload_to="images/", blank=True, verbose_name="Изображение"
    )
    slug = models.SlugField(
        max_length=255,
        db_index=True,
        blank=True,
        unique=True,
        verbose_name="URL",
    )
    cat = models.ForeignKey(
        to="Category", on_delete=models.SET_NULL, null=True, verbose_name="Категория"
    )

    def get_absolute_url(self):
        return reverse("myapp:product", kwargs={"product_slug": self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        db_table = "product"


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название")
    slug = models.SlugField(max_length=255, unique=True, verbose_name="URL")

    def get_absolute_url(self):
        return reverse("myapp:category", kwargs={"category_slug": self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        db_table = "category"

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/myapp/forms.py
from django import forms
from .models import Category, Product


class addProductForm(forms.ModelForm):
    cat = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        label="Категория",
        empty_label="Категория не выбрана",
    )

    class Meta:
        model = Product
        fields = ["title", "description", "price", "image", "cat", "slug"]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form__field"}),
            "description": forms.TextInput(attrs={"class": "form__field"}),
            "price": forms.NumberInput(attrs={"class": "form__field"}),
            "image": forms.FileInput(attrs={"class": "form__field"}),
            "cat": forms.Select(attrs={"class": "form__field"}),
            "slug": forms.TextInput(attrs={"class": "form__field"}),
        }

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        label="Логин", widget=forms.TextInput(attrs={"class": "form_input"})
    )
    password = forms.CharField(
        label="Пароль", widget=forms.PasswordInput(attrs={"class": "form_input"})
    )

    # class Meta:
    #     model = get_user_model()
    #     fields = ["username", "password"]

mysite/myapp/views.py
from django.db.models.base import Model as Model
from .models import Product, Category
from django.shortcuts import get_object_or_404, get_list_or_404
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .utils import DataMixin
from django.db.models import Q
from django.shortcuts import render, redirect
from .forms import addProductForm
from django.urls import reverse_lazy


class TechHome(DataMixin, TemplateView):
    """Главная страница"""

    template_name = "myapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)


class TechCategory(DataMixin, ListView):
    """Просмотр категории"""

    template_name = "myapp/products.html"
    context_object_name = "items"
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

    def get_queryset(self):
        if self.request.GET.get("search"):
            return get_list_or_404(
                Product,
                Q(title__icontains=self.request.GET.get("search"))
                | Q(description__icontains=self.request.GET.get("search")),
            )
        elif self.kwargs.get("category_slug") == "all":
            return Product.objects.all()
        else:
            return get_list_or_404(Product, cat__slug=self.kwargs.get("category_slug"))


class ShowProduct(DataMixin, DetailView):
    """Просмотр продукта"""

    model = Product
    template_name = "myapp/product_item.html"
    context_object_name = "item"
    slug_url_kwarg = "product_slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context)

    def get_object(self, queryset=None):
        return get_object_or_404(Product, slug=self.kwargs.get(self.slug_url_kwarg))


class addProduct(CreateView):
    """Добавление продукта"""

    form_class = addProductForm
    template_name = "myapp/add_product.html"
    extra_context = {"categories": Category.objects.all()}


class UpdateProduct(UpdateView):
    """Редактирование продукта"""

    model = Product
    fields = ["title", "description", "price", "cat"]
    success_url = reverse_lazy("myapp:home")
    template_name = "myapp/add_product.html"
    extra_context = {"categories": Category.objects.all()}


class DeleteProduct(DeleteView):
    """Удаление продукта"""

    model = Product
    success_url = reverse_lazy("myapp:home")

mysite/users/views.py
from django.shortcuts import render

from django.contrib.auth import authenticate
from .forms import LoginUserForm
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout

from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy


class LoginUser(LoginView):
    """Вход пользователя"""

    form_class = LoginUserForm
    template_name = "users/login.html"
    extra_context = {"title": "Авторизация"}

mysite/myapp/templates/myapp/add_product.html
{% extends "base.html" %}

{% block content %}

<form action="" class="form-add-product" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<div>{{ form.non_field_form }}</div>
	{% for f in form %}
	<div class="form__group field"><label class="form__label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</div>
	{% endfor %}
	<p><button class="button-add-product" type="submit">Отправить</button></p>
</form>

{% endblock  %}

mysite/myapp/templates/myapp/index.html
{% extends "base.html" %}

{% block content %}
<h1>Домашняя страница</h1>
{% endblock  %}

mysite/myapp/templates/myapp/product_item.html
{% extends "base.html" %}

{% block content-list %}
<div class="product-item">
	{% if item.image %}
	<div class="wrapper-image">
		<img class="product-image" src="{{ item.image.url }}" alt="iphone 14 pro max">
	</div>
	{% endif %}
	<a href="{{ item.get_absolute_url }}">
		<h2 class="product-title">{{ item.title }}</h2>
	</a>
	<p class="product-price"><b>{{ item.price }}</b> $</p>
	<p class="product-desc">{{ item.description }}</p>
	<div class="buttons-wrapper">
		<form action="{% url 'myapp:updatePage' item.slug %}" method="post">
			{% csrf_token %}
			<input class="change-button" type="submit" value="Изменить">
		</form>
		<form action="{% url 'myapp:deletePage' item.slug %}" method="post">
			{% csrf_token %}
			<input class="change-button" type="submit" value="Удалить"/>
		</form>
	</div>
</div>
{% endblock  %}

mysite/myapp/templates/myapp/products.html
{% extends "base.html" %}
{% load static %}

{% block content-list %}
<ul class="products-list" style="list-style: none">
{% for item in items %}
	<li class="products-item">
		{% if item.image %}
		<div class="wrapper-image">
			<img class="product-image" src="{{ item.image.url }}" alt="iphone 14 pro max">
		</div>
		{% endif %}
		<a href="{{ item.get_absolute_url }}">
			<h2 class="product-title">{{ item.title }}</h2>
		</a>
		<p class="product-price"><b>{{ item.price }}</b> $</p>
		<p class="product-desc">{{ item.description|truncatechars:210 }}</p>
	</li>
{% endfor %}
</ul>
{% endblock  %}

{% block navigation %}
{% if page_obj.has_other_pages %}
<nav>
	<ul class="list-pages">
		{% if page_obj.has_previous %}
		<a href="?page={{ page_obj.previous_page_number}}">Назад</a>
		{% endif %}
		{% for page in paginator.page_range %}
		{% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
		<li class="{% if page_obj.number == page %}page-num-active{% else %}page-num{% endif %}">
			<a href="?page={{ page }}">{{ page }}</a>
		</li>
		{% endif %}
		{% endfor %}
		{% if page_obj.has_next %}
		<a href="?page={{ page_obj.next_page_number}}">Вперед</a>
		{% endif %}
	</ul>
</nav>
{% endif %}
{% endblock  %}

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static "myapp/css/style.css" %}">
	<title>Home Page</title>
</head>
<body>
	<div class="wrapper">
	<header class="header">
		<div class="logo-wrapper">
			<a href="{% url "myapp:home" %}">
				<img class="logo-img" src="{% static "myapp/images/logo.svg" %}" alt="logo">
			</a>
		</div>

		<div class="theme-popup">
			<input type="radio" name="theme" id="default" checked="">
			<input type="radio" name="theme" id="light">
			<input type="radio" name="theme" id="dark">
			<input type="checkbox" id="checkbox">
			<label for="checkbox" class="theme-popup__button">
			Все категории
			</label>
			<div class="theme-popup__list-container">

				<ul class="theme-popup__list">
					{% for category in categories %}
					<li>
						<a class="nav-item" href="{{ category.get_absolute_url }}">
							{{ category.title }}
						</a>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		
		<div class="form-wrapper" method="get">
			<form action="{% url "myapp:search" %}" class="search-form">
				<input type="search" name="search" placeholder="Искать здесь...">
				<button type="submit"></button>
			</form>
		</div>

		<div>
			<ul>
				<li>
					<a class="nav-item" href="{% url "users:login" %}">
						Войти
					</a>
				</li>
				<li>
					<form method="post" action="{% url "users:logout" %}">
						{% csrf_token %}
						<button type="submit">Logout</button>
					</form>
				</li>
				<li>
					<a class="nav-item" href="#">
						Корзина
					</a>
				</li>
			</ul>
		</div>
	</header>
</div>
<div class="list-wrapper">
	{% block content-list %}{% endblock %}
	{% block navigation %}{% endblock  %}
	{% block content %}{% endblock %}
</div>
</body>
</html>

mysite/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<div class="login-box">
	<h1 class="login-title">{{ title }}</h1>

	<form method="post">
		{% csrf_token %}
		<input type="hidden" name="next" value={{ next }}>	
		<div class="form-error">{{ form.non_field_errors }}</div>
		{% for field in form %}
		<div class="user-box">
			<label for="{{ field.id_for_label }}"></label>
			{{ field }}
		</div>
		<div>
			{{ field.errors }}
		</div>
		{% endfor %}
		<button type="submit">
			Login
		<span></span>
		</button>
	</form>
</div>
{% endblock  %}

mysite/users/templates/users/test.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
	{% csrf_token %}
	<div class="form-error">{{ form.non_field_errors }}</div>
	{% for field in form %}
	<div><label for="{{ field.id_for_label }}">{{ field.label }}</label>{{ field }}</div>
	<div class="form-error">{{ field.errors }}</div>
	{% endfor %}
	<div><button type="submit">Send</button></div>
</form>
{% endblock  %}